version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: leader-board-mysql
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: leader-board
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always

  redis:
    image: redis:7.0
    container_name: leader-board-redis
    ports:
      - "26379:6379"
    volumes:
      - redis-data:/data
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: leader-board-zookeeper
    ports:
      - "22181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: leader-board-kafka
    ports:
      - "29092:9092"
      - "29093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always

  kafka-ui:
    container_name: leader-board-kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "28080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: leader-board-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    restart: always

volumes:
  mysql-data:
  redis-data: