spring:
  datasource:
    url: jdbc:mysql://localhost:23306/leader-board?useSSL=false&serverTimezone=Asia/Seoul
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8082
exposed:
  drop:
    create: false

---

spring:
  profiles:
    active: performance-test

exposed:
  drop:
    create: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
#logging:
#  level:
#    root: error
